# Generated by Django 4.2.8 on 2024-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film',
            field=models.FileField(null=True, upload_to='film/', verbose_name='film video'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='resim',
            field=models.FileField(null=True, upload_to='filmler/', verbose_name='film resmi'),
        ),
    ]
