# Generated by Django 4.2.8 on 2024-01-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_film_alter_movie_resim'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='Movies',
        ),
    ]
